# Generated by Django 5.2.1 on 2025-05-29 01:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('properties', '0001_initial'),
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RentalContract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(verbose_name='Start Date')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='End Date')),
                ('due_day', models.IntegerField(default=10, help_text='Day of the month the rent is due (e.g., 10 for the 10th)', verbose_name='Due Day')),
                ('rent_amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Rent Amount')),
                ('contract_file', models.FileField(blank=True, null=True, upload_to='contracts_pdf/', verbose_name='Contract File (PDF)')),
                ('status', models.CharField(choices=[('active', 'Ativo'), ('closed', 'Encerrado'), ('pending', 'Pendente')], default='active', max_length=20, verbose_name='Status do Contrato')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owner_contracts', to='properties.owner', verbose_name='Owner')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rental_contracts', to='properties.property', verbose_name='Property')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rental_contracts', to='tenants.tenant', verbose_name='Tenant')),
            ],
            options={
                'verbose_name': 'Contrato de Aluguel',
                'verbose_name_plural': 'Contratos de Aluguel',
                'ordering': ['-start_date'],
            },
        ),
    ]
