# Generated by Django 5.2.1 on 2025-05-31 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rentalcontract',
            name='contract_text',
            field=models.TextField(blank=True, null=True, verbose_name='Cláusulas Contratuais'),
        ),
    ]
